plugins {
    id 'com.android.application'
}

android {
    namespace 'com.edii.eapregistration'
    compileSdk 35

    defaultConfig {
        applicationId 'com.edii.eapregistration'
        minSdk 24
        targetSdk 35
        versionCode 14
        versionName '2.5-permission-credit'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
