plugins {
    id 'com.android.application'
}

android {
    namespace 'com.edii.eapregistration'
    compileSdk 35

    defaultConfig {
        applicationId 'com.edii.eapregistration'
        minSdk 24
        targetSdk 35
        versionCode 7
        versionName '1.6-exact-pdf-template'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
