plugins {
    id 'com.android.application'
}

android {
    namespace 'com.edii.eapregistration'
    compileSdk 35

    defaultConfig {
        applicationId 'com.edii.eapregistration'
        minSdk 24
        targetSdk 35
        versionCode 12
        versionName '2.3-hal-sponsored-welcome'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
